### ISSUE TITLE
Add new margin and padding props

### ISSUE THREAD

**Issue by muuvmuuv** [cahamilton/css-property-sort-order-smacss#4]
It is now possible to add logical CSS properties, would be nice if you could include them and them to their affiliated group (best to add them after the old props to they override them in cases where people included both).

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties

Example:

```css
#header {
  margin-inline-start: 20px;
}
```
